#ifndef __NAVBOT_DODS_SHAREDDEFS_H_
#define __NAVBOT_DODS_SHAREDDEFS_H_

namespace dayofdefeatsource
{
	enum DoDTeam : int
	{
		DODTEAM_UNASSIGNED = 0,
		DODTEAM_SPECTATOR,
		DODTEAM_ALLIES,
		DODTEAM_AXIS
	};

	enum DoDClassType : int
	{
		DODCLASS_INVALID = -1,
		DODCLASS_RIFLEMAN = 0,
		DODCLASS_ASSAULT,
		DODCLASS_SUPPORT,
		DODCLASS_SNIPER,
		DODCLASS_MACHINEGUNNER,
		DODCLASS_ROCKET
	};
}

#endif // !__NAVBOT_DODS_SHAREDDEFS_H_
