import pathlib, os, argparse, subprocess, shutil, textwrap

parser = argparse.ArgumentParser(prog="Auto Version Generator", description="Python script to automatically generate version headers from git.")
parser.add_argument('-o', '--output', help='Path plus file name of the output file to write.', dest='output', required=True)
parser.add_argument('-b', '--branch', help='Branch name to get the commit count, if not specified, main is used.', dest='branch')
args = parser.parse_args()

if args.output == None:
  raise RuntimeError('--output file not set!')

def CheckGit():
  if shutil.which('git') == None:
    raise RuntimeError('Git not installed or not available in path!')

CheckGit()

branchname = 'main'

if args.branch != None:
  branchname = args.branch

commithash = subprocess.check_output(['git', 'log', '--pretty=format:%H', '-n', '1']).decode('utf-8').strip()
url = subprocess.check_output(['git', 'ls-remote', '--get-url', 'origin']).decode('utf-8').strip()
count = subprocess.check_output(['git', 'rev-list', '--count', branchname]).decode('utf-8').strip()
url = url.removesuffix('.git')

tag = None

try:
  tag = subprocess.check_output(['git', 'describe', '--tags', '--abbrev=0']).decode('utf-8').strip()
except subprocess.CalledProcessError:
  tag = "0.0.0"


path = os.path.abspath(os.path.normpath(args.output))
file = os.path.join(path, 'generated_version.h')

with open(file, 'wt') as file:
  values = {
    'git_hash': commithash,
    'git_hash_short': commithash[:8],
    'git_url': url,
    'git_rev_count': count,
    'git_tag': tag,
  }
  file.write(textwrap.dedent("""
    /* This file is automatically generated! DO NOT EDIT! */
    #ifndef __GENERATED_VERSION_HEADER_H_
    #define __GENERATED_VERSION_HEADER_H_

    #define GIT_COMMIT_HASH "{git_hash}"
    #define GIT_COMMIT_SHORT_HASH "{git_hash_short}"
    #define GIT_URL "{git_url}"
    #define GIT_REV_COUNT "{git_rev_count}"
    #define GIT_TAG "{git_tag}"

    #endif // __GENERATED_VERSION_HEADER_H_
  """).format(**values)[1:])